version: "3.8"

services:
  springboot-app:
    build: .
    container_name: skillswap
    ports:
      - "8080:8080"
    restart: always
    environment:
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}